# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 9ffdbb8
_src_path: gh:scipp/copier_template
description: ''
max_python: '3.10'
min_python: '3.10'
namespace_package: ''
nightly_deps: ''
orgname: scipp
prettyname: Testsecrets
projectname: testsecrets
related_projects: ''
year: 2024
